# Generated by Django 4.1.5 on 2023-04-21 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_product_sun_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sun_category',
            new_name='sub_category',
        ),
    ]
