# Generated by Django 4.1.5 on 2023-04-22 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_sub_category_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_category',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='sub_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='main.sub_category'),
            preserve_default=False,
        ),
    ]
