# Generated by Django 4.1.5 on 2023-04-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=3000),
            preserve_default=False,
        ),
    ]
