# Generated by Django 4.1.5 on 2023-05-14 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
    ]
